# Generated by Django 2.0 on 2019-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(max_length=2000, upload_to='')),
                ('brief', models.FileField(max_length=2000, upload_to='')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
