# Generated by Django 2.0 on 2019-04-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
